[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"

[fuzz]
  max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
  runs = 500

[invariant]
  call_override = false # Override unsafe external calls to perform reentrancy checks
  depth = 20            # Number of calls executed in one run
  fail_on_revert = true
  runs = 20

# Speed up compilation and tests during development
[profile.lite]
  optimizer = false

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = 'attributes_first'
  single_line_statement_blocks = 'preserve'
  quote_style = "double"
  tab_width = 4
  wrap_comments = false

[rpc_endpoints]
  localhost = "http://localhost:8545"
  sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
  mainnet = "https://eth.llamarpc.com"
  base = "https://base-rpc.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
